### ISSUE TITLE
Configuring the assests | Error in positioning

### ISSUE THREAD

**Issue by Zonalds** [shotstack/node-demos#2]
Hey I have a little problem with positioning in overlays:
I am using Node 12.

The code below is intended to play the TittleAssets on the topRight, but for some reason it appears on the center.

`   
```
 let titleAsset = new Shotstack.TitleAsset;
    titleAsset
        .setStyle('minimal')
        .setText('Hello World')
        .setSize('small');
```

    let title = new Shotstack.Clip;
    title
        .setAsset(titleAsset)
        .setStart(0)
        .setLength(5)
        .setPosition('topRight');` 

I also do have a few other minor questions;

What are other options other for .setStyles other than 'minimal'?
And how do I create a margin between the screen and the assets if I successfully placed them on ends like bottomRight, bottomLeft, topRight and topLeft?

**Comment by Zonalds** [comment]
I was able to find the problem with my configuration:

```
` let titleAsset = new Shotstack.TitleAsset;
    titleAsset
        .setStyle('minimal')
        .setText('Hello World')
        .setSize('small')
        .setPosition('topRight');
let title = new Shotstack.Clip;
```
```
title
    .setAsset(titleAsset)
    .setStart(0)
    .setLength(5)
   ` `
```

- ` .setPosition('topRight');` ought to be in the TittleAsset configuration not in clip configuration.

-  Alternative to  'minimal' for .setStyles are // minimal, blockbuster, vogue, sketchy, skinny, chunk, chunkLight, marker, future, subtitle and can be found at the docs [here](https://shotstack.io/docs/api/index.html?javascript--nodejs#tocs_titleasset).

- Creating margins can be done with .offSet and can be found at the doc [here](https://shotstack.io/docs/api/index.html?javascript--nodejs#tocs_offset)

**Comment by jeffski** [comment]
@Zonalds good to see you managed to work it out. While the Title asset is good for getting started and quickly creating titles and text I would advise using the HTML asset instead as it offers much more control over positioning, text alignment and wrapping using basic HTML and CSS. You can also use your own font.

We have a full guide here on how to use the HTML asset and custom fonts: https://shotstack.io/learn/html-custom-fonts/

API docs for the HTML asset here: https://shotstack.io/docs/api/#tocs_htmlasset

Supported HTML/CSS here: https://shotstack.gitbook.io/docs/guides/architecting-an-application/html-support
