### ISSUE TITLE
Error in list for filters

### ISSUE THREAD

**Issue by DblK** [shotstack/node-demos#6]
Hi,

In the example for filter, there are two main different from docs.
- `original` which is not documented
- `negative` in place of `invert` I guess

So either there is an issue in this example or there is some lack in the documentation.

**Comment by jeffski** [comment]
Hi, I know this is old so it may have been resolved - `negative` is the correct filter name. I see `negative` used in the example and our docs. Maybe that was fixed.

`original` is in the list but it is never actually applied as a filter or sent as a filter to the API. It is just used as a label to display the text `original` for the video clip that has no filter applied.

As far as I can tell everything is the way it should be.
