### ISSUE TITLE
Creating slideshow using local image paths

### ISSUE THREAD

**Issue by lhttushargoplani** [shotstack/node-demos#8]
Hi, I want to create a slideshow using local image path and local music path. Is it possible? If it is possible then how can we do that ?

**Comment by jeffski** [comment]
Hi,
All images and assets need to be available somewhere online. The API is a hosted service and can't access local file systems. You can upload your assets to our Ingestion service which will make your files available online, docs here: https://shotstack.io/docs/guide/ingesting-footage/ingestion. Our host them your self in any online storage service. You can use signed URL's to secure assets so no-one else has access if security is an issue.
